export { default as Header } from '@/components/organisms/MainHeader.vue'
export { default as DashboardList } from '@/components/organisms/DashboardList.vue'
export { default as DashboardViewer } from '@/components/organisms/DashboardViewer.vue'
export { default as CarMilageForm } from '~/components/organisms/CarMilageForm.vue'
export { default as CarMilageTable } from '~/components/organisms/CarMilageTable.vue'
