export { default as Avatar } from '@/components/atoms/Avatar.vue'
export { default as Button } from '@/components/atoms/Button.vue'
export { default as Input } from '@/components/atoms/Input.vue'
export { default as Select } from '@/components/atoms/Select.vue'
export { default as Value } from '@/components/atoms/Value.vue'
