export { default as Avatar } from '@/components/atoms/avatar.vue'
export { default as Button } from '@/components/atoms/button.vue'
export { default as Input } from '@/components/atoms/input.vue'
export { default as Select } from '@/components/atoms/select.vue'
export { default as Value } from '@/components/atoms/value.vue'
